"""add creatde by in OrderStatusHistory table

Revision ID: 00befab20251
Revises: 572d50cc929b
Create Date: 2024-08-27 15:54:39.158105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00befab20251'
down_revision: Union[str, None] = '572d50cc929b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'is_google_ad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('is_google_ad', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->yes,0-No'))
    # ### end Alembic commands ###
