"""add file type in article files

Revision ID: 020ea56e1cb0
Revises: 3ace96c5bc2d
Create Date: 2024-08-05 10:27:46.015638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '020ea56e1cb0'
down_revision: Union[str, None] = '3ace96c5bc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('topic_se_review_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('topic_ce_review_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('topic_ce_cmnt_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('topic_se_cmnt_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('topic_ce_approved_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('content_se_review_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('content_ce_review_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('content_ce_cmnt_at', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('content_se_cmnt_at', sa.DateTime(), nullable=True))
    op.drop_column('article', 'topic_cmnt_at')
    op.drop_column('article', 'content_review_at')
    op.drop_column('article', 'topic_approved_at')
    op.drop_column('article', 'topic_review_at')
    op.drop_column('article', 'content_cmnt_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content_cmnt_at', mysql.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('topic_review_at', mysql.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('topic_approved_at', mysql.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('content_review_at', mysql.DATETIME(), nullable=True))
    op.add_column('article', sa.Column('topic_cmnt_at', mysql.DATETIME(), nullable=True))
    op.drop_column('article', 'content_se_cmnt_at')
    op.drop_column('article', 'content_ce_cmnt_at')
    op.drop_column('article', 'content_ce_review_at')
    op.drop_column('article', 'content_se_review_at')
    op.drop_column('article', 'topic_ce_approved_at')
    op.drop_column('article', 'topic_se_cmnt_at')
    op.drop_column('article', 'topic_ce_cmnt_at')
    op.drop_column('article', 'topic_ce_review_at')
    op.drop_column('article', 'topic_se_review_at')
    # ### end Alembic commands ###
