"""change

Revision ID: 0323a95273b0
Revises: 06ccdd3778cb
Create Date: 2024-07-18 09:09:10.686247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0323a95273b0'
down_revision: Union[str, None] = '06ccdd3778cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_comment='0->new,1-not submitted,2->SE approved,3-CE Approved,4-On Hold',
               existing_nullable=True)
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_comment='0->new,1-not submitted,2->SE approved,3-CE Approved,4-On Hold',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='0->new,1-not submitted,2->SE approved,3-CE Approved,4-On Hold',
               existing_comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_nullable=True)
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='0->new,1-not submitted,2->SE approved,3-CE Approved,4-On Hold',
               existing_comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_nullable=True)
    # ### end Alembic commands ###
