"""dffds

Revision ID: 049151085e41
Revises: a73e73479411
Create Date: 2024-08-09 15:31:58.815003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049151085e41'
down_revision: Union[str, None] = 'a73e73479411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('past_designation', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'past_designation')
    # ### end Alembic commands ###
