"""add user details  column in user table

Revision ID: 07a8edce6bdd
Revises: f19e90e9c9a0
Create Date: 2024-07-26 09:53:32.486993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a8edce6bdd'
down_revision: Union[str, None] = 'f19e90e9c9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pan_number', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('educational_qualification', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('area_of_interest', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('previous_experience', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('experience_in_relevent_field', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'experience_in_relevent_field')
    op.drop_column('user', 'previous_experience')
    op.drop_column('user', 'area_of_interest')
    op.drop_column('user', 'educational_qualification')
    op.drop_column('user', 'pan_number')
    # ### end Alembic commands ###
