"""add ad table

Revision ID: 095e36c626d6
Revises: 8c5030c120fb
Create Date: 2024-07-16 17:29:57.859686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '095e36c626d6'
down_revision: Union[str, None] = '8c5030c120fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediafiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=250), nullable=True),
    sa.Column('meta_keywords', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('content_type', mysql.TINYINT(), nullable=True, comment='1->Advertisement,2->others'),
    sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->shorts,2->Video'),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('advertisement')
    op.add_column('brandcampaigns', sa.Column('img_alter', sa.String(length=250), nullable=True))
    op.add_column('brandcampaigns', sa.Column('img_path', sa.Text(), nullable=True))
    op.drop_column('brandcampaigns', 'media_path')
    op.add_column('category', sa.Column('img_alter', sa.String(length=250), nullable=True))
    op.add_column('category', sa.Column('img_path', sa.Text(), nullable=True))
    op.drop_column('category', 'media_path')
    op.add_column('subcategory', sa.Column('alt_img', sa.String(length=250), nullable=True))
    op.add_column('subcategory', sa.Column('img_path', sa.Text(), nullable=True))
    op.drop_column('subcategory', 'media_path')
    op.add_column('user', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('alt_image', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('resume_path', sa.Text(), nullable=True))
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'resume_path')
    op.drop_column('user', 'alt_image')
    op.drop_column('user', 'image_path')
    op.add_column('subcategory', sa.Column('media_path', mysql.TEXT(), nullable=True))
    op.drop_column('subcategory', 'img_path')
    op.drop_column('subcategory', 'alt_img')
    op.add_column('category', sa.Column('media_path', mysql.TEXT(), nullable=True))
    op.drop_column('category', 'img_path')
    op.drop_column('category', 'img_alter')
    op.add_column('brandcampaigns', sa.Column('media_path', mysql.TEXT(), nullable=True))
    op.drop_column('brandcampaigns', 'img_path')
    op.drop_column('brandcampaigns', 'img_alter')
    op.create_table('advertisement',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('meta_title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('meta_description', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('meta_keywords', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('seo_url', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('media_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'),
    sa.Column('media_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->shorts,-1->Video'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='advertisement_ibfk_1'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='advertisement_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mediafiles')
    # ### end Alembic commands ###
