"""add file type in article files

Revision ID: 0a6590695ba4
Revises: e136c2274327
Create Date: 2024-08-01 12:49:55.011434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6590695ba4'
down_revision: Union[str, None] = 'e136c2274327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('youtupe_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'youtupe_link')
    # ### end Alembic commands ###
