"""add is_active in category table

Revision ID: 0ac3e03a2911
Revises: 6669f1d8cc48
Create Date: 2024-07-31 12:35:16.782403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac3e03a2911'
down_revision: Union[str, None] = '6669f1d8cc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'img_path')
    # ### end Alembic commands ###
