"""add reward point

Revision ID: 0efcd04fd305
Revises: bb82534d2fcc
Create Date: 2024-10-09 17:06:29.240935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efcd04fd305'
down_revision: Union[str, None] = 'bb82534d2fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('choosen_images', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'choosen_images')
    # ### end Alembic commands ###
