"""add article title in article

Revision ID: 0f0df67e8287
Revises: ae17c105253b
Create Date: 2024-07-29 18:00:21.891451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f0df67e8287'
down_revision: Union[str, None] = 'ae17c105253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('is_topic', mysql.TINYINT(), nullable=True, comment='1->yes'))
    op.add_column('article_history', sa.Column('is_content', mysql.TINYINT(), nullable=True, comment='1->yes'))
    op.drop_column('article_history', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'))
    op.drop_column('article_history', 'is_content')
    op.drop_column('article_history', 'is_topic')
    # ### end Alembic commands ###
