"""add tax type

Revision ID: 1255954bad02
Revises: 146259d819f8
Create Date: 2024-11-27 16:29:29.593780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1255954bad02'
down_revision: Union[str, None] = '146259d819f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'media_position',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.Integer(),
               comment='1-Home Page Banner Ad,2-Home Page Left Pillar Ad,3-Home Page Right Pillar Ad,4-Article Page Top Banner Ad,5-Article Page Mid-Strip Banner Ad,6-Article Page Right Banner Ad,7- Website Bottom Banner Ad',
               existing_comment='1->Top,2-Bottom,3-right,4-Left',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'media_position',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=250),
               comment='1->Top,2-Bottom,3-right,4-Left',
               existing_comment='1-Home Page Banner Ad,2-Home Page Left Pillar Ad,3-Home Page Right Pillar Ad,4-Article Page Top Banner Ad,5-Article Page Mid-Strip Banner Ad,6-Article Page Right Banner Ad,7- Website Bottom Banner Ad',
               existing_nullable=True)
    # ### end Alembic commands ###
