"""Initial migration

Revision ID: 144287921a7d
Revises: 9def590ef5cc
Create Date: 2024-09-21 11:39:46.321815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '144287921a7d'
down_revision: Union[str, None] = '9def590ef5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('employement_type', mysql.TINYINT(), nullable=True, comment='1-full-time, 2-part-time, 3-contract, 4-internship, 5-temporary,6-hyper'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'employement_type')
    # ### end Alembic commands ###
