"""add tax type

Revision ID: 146259d819f8
Revises: 14d9dd08e829
Create Date: 2024-11-27 10:27:02.963965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '146259d819f8'
down_revision: Union[str, None] = '14d9dd08e829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'media_position',
               existing_type=mysql.TINYINT(),
               type_=sa.String(length=250),
               existing_comment='1->Top,2-Bottom,3-right,4-Left',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'media_position',
               existing_type=sa.String(length=250),
               type_=mysql.TINYINT(),
               existing_comment='1->Top,2-Bottom,3-right,4-Left',
               existing_nullable=True)
    # ### end Alembic commands ###
