"""add reward point

Revision ID: 14d9dd08e829
Revises: 0efcd04fd305
Create Date: 2024-10-09 17:07:27.499176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14d9dd08e829'
down_revision: Union[str, None] = '0efcd04fd305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('choosed_images', sa.String(length=500), nullable=True))
    op.drop_column('media_files', 'choosen_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('choosen_images', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('media_files', 'choosed_images')
    # ### end Alembic commands ###
