"""add ad table

Revision ID: 17a02c750263
Revises: 48ddf49594a5
Create Date: 2024-07-16 17:46:34.244976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '17a02c750263'
down_revision: Union[str, None] = '48ddf49594a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True, comment='journal tab id'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_history')
    # ### end Alembic commands ###
