"""add creatde by in OrderStatusHistory table

Revision ID: 1941e6482dba
Revises: 4527fd880bf8
Create Date: 2024-08-24 11:53:36.056541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1941e6482dba'
down_revision: Union[str, None] = '4527fd880bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
