"""Update article table schema

Revision ID: 197aa35e085d
Revises: 8cb511435f9c
Create Date: 2024-07-17 11:54:23.019233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '197aa35e085d'
down_revision: Union[str, None] = '8cb511435f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_journalist', mysql.TINYINT(), nullable=True, comment='1-yes'))
    op.drop_column('article', 'is_articleist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_articleist', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-yes'))
    op.drop_column('article', 'is_journalist')
    # ### end Alembic commands ###
