"""add creatde by in OrderStatusHistory table

Revision ID: 1a77b5500279
Revises: 9bb195f54e6b
Create Date: 2024-08-28 18:13:33.666698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a77b5500279'
down_revision: Union[str, None] = '9bb195f54e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('topic', sa.String(length=250), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('is_choosed', mysql.TINYINT(), nullable=True, comment='1->yes'),
    sa.Column('is_approved', mysql.TINYINT(), nullable=True, comment='1->no,2-yes'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'article', 'article_topic', ['article_topic_id'], ['id'])
    op.create_foreign_key(None, 'article_files', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_history', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'article_history', 'article_topic', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'email_history', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'article', ['article_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'article_topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'email_history', type_='foreignkey')
    op.drop_constraint(None, 'article_history', type_='foreignkey')
    op.drop_constraint(None, 'article_history', type_='foreignkey')
    op.drop_constraint(None, 'article_files', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_table('article_topic')
    # ### end Alembic commands ###
