"""add file type in article files

Revision ID: 1c8630c2d8c2
Revises: 020ea56e1cb0
Create Date: 2024-08-05 11:33:51.903496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1c8630c2d8c2'
down_revision: Union[str, None] = '020ea56e1cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('media_orientation', mysql.TINYINT(), nullable=True, comment='1->Portrait,2-Landscape'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'media_orientation')
    # ### end Alembic commands ###
