"""add creatde by in OrderStatusHistory table

Revision ID: 223cf713af5c
Revises: 62c42b2b1af1
Create Date: 2024-08-24 11:55:39.896763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '223cf713af5c'
down_revision: Union[str, None] = '62c42b2b1af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('save_for_later', mysql.TINYINT(), nullable=True, comment='1->yes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'save_for_later')
    # ### end Alembic commands ###
