"""change

Revision ID: 26d449127761
Revises: eefdd0c77fb8
Create Date: 2024-07-18 15:13:59.321919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26d449127761'
down_revision: Union[str, None] = 'eefdd0c77fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_request',
               existing_type=mysql.TINYINT(),
               comment='1->Interview Process,2->Accepted,0->Request,-1 ->rejected',
               existing_comment='1->Accepted,0->Request,-1 ->rejected',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_request',
               existing_type=mysql.TINYINT(),
               comment='1->Accepted,0->Request,-1 ->rejected',
               existing_comment='1->Interview Process,2->Accepted,0->Request,-1 ->rejected',
               existing_nullable=True)
    # ### end Alembic commands ###
