"""add file type in article files

Revision ID: 27b47e7cd1bf
Revises: dbb3e6c28146
Create Date: 2024-08-07 09:46:17.466375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b47e7cd1bf'
down_revision: Union[str, None] = 'dbb3e6c28146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_settings', sa.Column('wepro_text', sa.Text(), nullable=True))
    op.add_column('cms_settings', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('cms_settings', sa.Column('our_teams', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_settings', 'our_teams')
    op.drop_column('cms_settings', 'about')
    op.drop_column('cms_settings', 'wepro_text')
    # ### end Alembic commands ###
