"""skjsa

Revision ID: 29c499b21eb9
Revises: f34105621105
Create Date: 2024-07-24 18:24:11.956782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c499b21eb9'
down_revision: Union[str, None] = 'f34105621105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_settings', sa.Column('twitter', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_settings', 'twitter')
    # ### end Alembic commands ###
