"""add creatde by in OrderStatusHistory table

Revision ID: 2bbf4d56a3b7
Revises: 997660209628
Create Date: 2024-08-29 09:16:57.000243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bbf4d56a3b7'
down_revision: Union[str, None] = '997660209628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_top_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_image', sa.String(length=500), nullable=True),
    sa.Column('top_url', sa.String(length=500), nullable=True),
    sa.Column('media_files_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_files_id'], ['media_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('article_topic', 'is_approved',
               existing_type=mysql.TINYINT(),
               comment='1->comment,2-approved',
               existing_comment='1->no,2-yes',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_topic', 'is_approved',
               existing_type=mysql.TINYINT(),
               comment='1->no,2-yes',
               existing_comment='1->comment,2-approved',
               existing_nullable=True)
    op.drop_table('media_top_images')
    # ### end Alembic commands ###
