"""initial commit

Revision ID: 31554d4ad497
Revises: 5ac2c14ce82b
Create Date: 2024-08-31 09:44:49.031054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31554d4ad497'
down_revision: Union[str, None] = '5ac2c14ce82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_topic', 'description',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_topic', 'description',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
