"""Initial migration

Revision ID: 348ef923d556
Revises: 5b4d42f5fa0e
Create Date: 2024-09-24 14:05:36.029552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348ef923d556'
down_revision: Union[str, None] = '5b4d42f5fa0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_files', sa.Column('raw_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_files', 'raw_file')
    # ### end Alembic commands ###
