"""add creatde by in OrderStatusHistory table

Revision ID: 364d0e16f7c8
Revises: 96929ce4768d
Create Date: 2024-08-24 11:55:09.385779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364d0e16f7c8'
down_revision: Union[str, None] = '96929ce4768d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
