"""add user details  column in user table

Revision ID: 39ba1a8d5b0d
Revises: ce2df79e776b
Create Date: 2024-07-26 10:10:03.254040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39ba1a8d5b0d'
down_revision: Union[str, None] = 'ce2df79e776b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup',
               existing_nullable=True)
    # ### end Alembic commands ###
