"""add ad table

Revision ID: 3ca150f6851f
Revises: edb41b80e62c
Create Date: 2024-07-16 15:48:12.296170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3ca150f6851f'
down_revision: Union[str, None] = 'edb41b80e62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('media_path', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='category tab id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('category', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment='category order no',
               existing_comment='brand campaigngs order no',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment='brand campaigngs order no',
               existing_comment='category order no',
               existing_nullable=True)
    op.drop_table('subcategory')
    # ### end Alembic commands ###
