"""add user details  column in user table

Revision ID: 3ce74d0e5087
Revises: b4422308ec6c
Create Date: 2024-07-26 13:59:07.656445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce74d0e5087'
down_revision: Union[str, None] = 'b4422308ec6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('requested_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('rejected_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rejected_at')
    op.drop_column('user', 'approved_at')
    op.drop_column('user', 'requested_at')
    # ### end Alembic commands ###
