"""change

Revision ID: 3cf7c8c2cedb
Revises: bf6b1083b64f
Create Date: 2024-07-19 13:58:09.237066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf7c8c2cedb'
down_revision: Union[str, None] = 'bf6b1083b64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_history', sa.Column('user_id', sa.Integer(), nullable=True, comment='user tab id'))
    op.create_foreign_key(None, 'email_history', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_history', type_='foreignkey')
    op.drop_column('email_history', 'user_id')
    # ### end Alembic commands ###
