"""add ad table

Revision ID: 3dd1170ed284
Revises: ac3b61f91116
Create Date: 2024-07-16 15:02:56.772644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd1170ed284'
down_revision: Union[str, None] = 'ac3b61f91116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('advertisement', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('advertisement', sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'))
    op.add_column('advertisement', sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'))
    op.create_foreign_key(None, 'advertisement', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'advertisement', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.drop_constraint(None, 'advertisement', type_='foreignkey')
    op.drop_column('advertisement', 'updated_by')
    op.drop_column('advertisement', 'created_by')
    op.drop_column('advertisement', 'updated_at')
    op.drop_column('advertisement', 'created_at')
    # ### end Alembic commands ###
