"""Initial migration

Revision ID: 3f4be8d97ada
Revises: ce7fe23c6dd0
Create Date: 2024-09-24 14:55:31.872481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4be8d97ada'
down_revision: Union[str, None] = 'ce7fe23c6dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_files', 'raw_file',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_files', 'raw_file',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
