"""add creatde by in OrderStatusHistory table

Revision ID: 4388558e57ec
Revises: 68406a4b9b14
Create Date: 2024-08-22 14:36:38.284093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4388558e57ec'
down_revision: Union[str, None] = '68406a4b9b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('article_type', mysql.TINYINT(), nullable=True, comment='1->topic,2-content'))
    op.drop_column('article_history', 'is_content')
    op.drop_column('article_history', 'is_topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('is_topic', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->yes'))
    op.add_column('article_history', sa.Column('is_content', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->yes'))
    op.drop_column('article_history', 'article_type')
    # ### end Alembic commands ###
