"""add ad table

Revision ID: 439e31c9d180
Revises: cce567dd9b8e
Create Date: 2024-07-17 16:47:25.774005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '439e31c9d180'
down_revision: Union[str, None] = 'cce567dd9b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_ibfk_2', 'article', type_='foreignkey')
    op.drop_constraint('article_ibfk_4', 'article', type_='foreignkey')
    op.drop_column('article', 'city_id')
    op.drop_column('article', 'state_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('state_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('city_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('article_ibfk_4', 'article', 'states', ['state_id'], ['id'])
    op.create_foreign_key('article_ibfk_2', 'article', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
