"""add creatde by in OrderStatusHistory table

Revision ID: 4527fd880bf8
Revises: 3f1439325020
Create Date: 2024-08-24 10:07:11.614161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4527fd880bf8'
down_revision: Union[str, None] = '3f1439325020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'content_type',
               existing_type=mysql.TINYINT(),
               comment='1->Advertisement,2->Banners,3-youtube,4-shorts',
               existing_comment='1->Advertisement,2->Banners,3-youtube',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'content_type',
               existing_type=mysql.TINYINT(),
               comment='1->Advertisement,2->Banners,3-youtube',
               existing_comment='1->Advertisement,2->Banners,3-youtube,4-shorts',
               existing_nullable=True)
    # ### end Alembic commands ###
