"""add user details  column in user table

Revision ID: 456c67ede120
Revises: efd67a3931b4
Create Date: 2024-07-26 12:10:09.160359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '456c67ede120'
down_revision: Union[str, None] = 'efd67a3931b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_content', sa.String(length=2500), nullable=True))
    op.drop_column('article', 'topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('topics', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('article', 'article_content')
    # ### end Alembic commands ###
