"""Initial migration

Revision ID: 46880a100250
Revises: 144287921a7d
Create Date: 2024-09-21 11:43:58.118993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46880a100250'
down_revision: Union[str, None] = '144287921a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('employment_type', mysql.TINYINT(), nullable=True, comment='1-full-time, 2-part-time, 3-contract, 4-internship, 5-temporary,6-hyper'))
    op.drop_column('user', 'employement_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('employement_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-full-time, 2-part-time, 3-contract, 4-internship, 5-temporary,6-hyper'))
    op.drop_column('user', 'employment_type')
    # ### end Alembic commands ###
