"""add creatde by in OrderStatusHistory table

Revision ID: 47bfa4898fab
Revises: 9621b915bd99
Create Date: 2024-08-23 12:16:39.033981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bfa4898fab'
down_revision: Union[str, None] = '9621b915bd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('topic_id', sa.Integer(), nullable=True, comment='article topic id'))
    op.create_foreign_key(None, 'notification', 'article_topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'topic_id')
    # ### end Alembic commands ###
