"""add file type in article files

Revision ID: 4def81aa85a2
Revises: 31c4e537bf6a
Create Date: 2024-08-05 09:18:48.573838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4def81aa85a2'
down_revision: Union[str, None] = '31c4e537bf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_history', 'content_status',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved),6-Deadline',
               existing_comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_history', 'content_status',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved)',
               existing_comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved),6-Deadline',
               existing_nullable=True)
    # ### end Alembic commands ###
