"""add ad table

Revision ID: 520a763e16b2
Revises: 8d19ffef2cc4
Create Date: 2024-07-16 16:26:49.704151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '520a763e16b2'
down_revision: Union[str, None] = '8d19ffef2cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('journal', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journal', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'journal', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.drop_column('journal', 'city_id')
    op.drop_column('journal', 'state_id')
    # ### end Alembic commands ###
