"""Update article table schema

Revision ID: 52bbd4d5ada2
Revises: 
Create Date: 2024-07-17 10:30:40.475246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52bbd4d5ada2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', mysql.TINYINT(), nullable=True, comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6->Digital Marketing strategist,7-journalist,8-Member'),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alternative_no', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('bank', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=500), nullable=True),
    sa.Column('approval_status', mysql.TINYINT(), nullable=True, comment='1->Accepted,0->Request,-1 ->rejected'),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), nullable=True, comment='1->active,0->inactive'),
    sa.Column('img_path', sa.String(length=255), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('reset_key', sa.String(length=255), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('resume_path', sa.Text(), nullable=True),
    sa.Column('otp_expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('renewed_at', sa.DateTime(), nullable=True),
    sa.Column('device_type', mysql.TINYINT(display_width=1), nullable=True, comment='1-Android, 2-iOS'),
    sa.Column('validity', mysql.TINYINT(display_width=1), nullable=True, comment='0-Expired, 1- Lifetime'),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('push_device_id', sa.String(length=255), nullable=True),
    sa.Column('device_ip', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('topic', sa.String(length=250), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=250), nullable=True),
    sa.Column('meta_keywords', sa.String(length=250), nullable=True),
    sa.Column('submition_date', sa.Date(), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('topic_approved', mysql.TINYINT(), nullable=True, comment='0->waiting,1->SE approved,2-CE Approved,3-Published,4-holding'),
    sa.Column('content_approved', mysql.TINYINT(), nullable=True, comment='0->waiting,1->SE approved,2-CE Approved,3-published,4-holding'),
    sa.Column('is_articleist', mysql.TINYINT(), nullable=True, comment='1-yes'),
    sa.Column('sub_editor_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('chief_editor_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['chief_editor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['sub_editor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brandcampaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=250), nullable=True),
    sa.Column('img_path', sa.Text(), nullable=True),
    sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->image,2->Gif'),
    sa.Column('brand_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='brand campaigngs order no'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=250), nullable=True),
    sa.Column('img_path', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='category order no'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_play', sa.String(length=255), nullable=True),
    sa.Column('app_store', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('threads', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('youtube', sa.String(length=255), nullable=True),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediafiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=250), nullable=True),
    sa.Column('meta_keywords', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('content_type', mysql.TINYINT(), nullable=True, comment='1->Advertisement,2->others'),
    sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->shorts,2->Video'),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articlefiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='journal tab id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articlehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='article tab id'),
    sa.Column('sub_editor_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('chief_editor_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('journalist_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('sub_editor_notify', mysql.TINYINT(), nullable=True, comment='1->Notify,2->Read'),
    sa.Column('chief_editor_notify', mysql.TINYINT(), nullable=True, comment='1->Notify,2->Read'),
    sa.Column('journalist_notify', mysql.TINYINT(), nullable=True, comment='1->Notify,2->Read'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['chief_editor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['journalist_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sub_editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='article tab id'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=250), nullable=True),
    sa.Column('img_path', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='sub category order no'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='category tab id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategory')
    op.drop_table('email_history')
    op.drop_table('articlehistory')
    op.drop_table('articlefiles')
    op.drop_table('mediafiles')
    op.drop_table('cms_settings')
    op.drop_table('category')
    op.drop_table('brandcampaigns')
    op.drop_table('article')
    op.drop_table('api_tokens')
    op.drop_table('user')
    op.drop_table('cities')
    op.drop_table('states')
    # ### end Alembic commands ###
