"""add user and apitoken table

Revision ID: 52e493acc602
Revises: 
Create Date: 2024-07-16 10:46:26.134314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '52e493acc602'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', mysql.TINYINT(), nullable=True, comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6->Digital Marketing strategist,7-journalist,8-Member'),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_no', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('bank', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=500), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('delar_id', sa.Integer(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), nullable=True, comment='1->active,0->inactive'),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('reset_key', sa.String(length=255), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('otp_expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['delar_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('renewed_at', sa.DateTime(), nullable=True),
    sa.Column('device_type', mysql.TINYINT(display_width=1), nullable=True, comment='1-Android, 2-iOS'),
    sa.Column('validity', mysql.TINYINT(display_width=1), nullable=True, comment='0-Expired, 1- Lifetime'),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('push_device_id', sa.String(length=255), nullable=True),
    sa.Column('device_ip', sa.String(length=255), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_tokens')
    op.drop_table('user')
    # ### end Alembic commands ###
