"""Initial migration

Revision ID: 5363c71c2070
Revises: a5eee709a218
Create Date: 2024-09-28 15:10:14.339645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5363c71c2070'
down_revision: Union[str, None] = 'a5eee709a218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'ratings', ['rating_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'rating_id')
    # ### end Alembic commands ###
