"""add is_active in category table

Revision ID: 56268281acfb
Revises: 052e63e0ed8d
Create Date: 2024-07-30 10:07:08.789499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56268281acfb'
down_revision: Union[str, None] = '052e63e0ed8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_active', mysql.TINYINT(), nullable=True, comment='1->active,0->inactive'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_active')
    # ### end Alembic commands ###
