"""add creatde by in OrderStatusHistory table

Revision ID: 572d50cc929b
Revises: 986c601190f7
Create Date: 2024-08-27 15:54:18.619907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572d50cc929b'
down_revision: Union[str, None] = '986c601190f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('top_url', sa.String(length=500), nullable=True))
    op.add_column('media_files', sa.Column('left_url', sa.String(length=500), nullable=True))
    op.add_column('media_files', sa.Column('right_url', sa.String(length=500), nullable=True))
    op.add_column('media_files', sa.Column('bottom_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'bottom_url')
    op.drop_column('media_files', 'right_url')
    op.drop_column('media_files', 'left_url')
    op.drop_column('media_files', 'top_url')
    # ### end Alembic commands ###
