"""initial commit

Revision ID: 5ac2c14ce82b
Revises: 4228474f4251
Create Date: 2024-08-31 09:43:37.422303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5ac2c14ce82b'
down_revision: Union[str, None] = '4228474f4251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'description',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('sub_category', 'description',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_category', 'description',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('category', 'description',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
