"""add ad table

Revision ID: 5afa5eb3b4d4
Revises: 6d00a885d4bf
Create Date: 2024-07-16 14:39:13.212260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5afa5eb3b4d4'
down_revision: Union[str, None] = '6d00a885d4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_url', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=250), nullable=True),
    sa.Column('meta_keywords', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('default_img_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', mysql.TINYINT(), nullable=True, comment='1->shorts,-1->Video'),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement')
    # ### end Alembic commands ###
