"""Initial migration

Revision ID: 5b4d42f5fa0e
Revises: 46880a100250
Create Date: 2024-09-21 11:45:36.015374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4d42f5fa0e'
down_revision: Union[str, None] = '46880a100250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('careers', 'sort_order')
    # ### end Alembic commands ###
