"""add creatde by in OrderStatusHistory table

Revision ID: 5c2f3a413308
Revises: db7d3ddf349a
Create Date: 2024-08-29 15:49:05.063040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2f3a413308'
down_revision: Union[str, None] = 'db7d3ddf349a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
