"""add ad table

Revision ID: 5f611be9c48e
Revises: d04be0db6384
Create Date: 2024-07-17 17:51:12.670025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f611be9c48e'
down_revision: Union[str, None] = 'd04be0db6384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('topics', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'topics')
    # ### end Alembic commands ###
