"""add user and apitoken table

Revision ID: 603372772341
Revises: b173c5bdcf91
Create Date: 2024-07-16 12:40:34.484350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603372772341'
down_revision: Union[str, None] = 'b173c5bdcf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'approved_by')
    # ### end Alembic commands ###
