"""add creatde by in OrderStatusHistory table

Revision ID: 6957cda7828c
Revises: 47bfa4898fab
Create Date: 2024-08-23 12:18:48.804568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6957cda7828c'
down_revision: Union[str, None] = '47bfa4898fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'notification_type',
               existing_type=mysql.TINYINT(),
               comment='1->topic,2-content,3-Requested Account,4->editors topic',
               existing_comment='1->topic,2-content,3-Requested Account',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'notification_type',
               existing_type=mysql.TINYINT(),
               comment='1->topic,2-content,3-Requested Account',
               existing_comment='1->topic,2-content,3-Requested Account,4->editors topic',
               existing_nullable=True)
    # ### end Alembic commands ###
