"""add creatde by in OrderStatusHistory table

Revision ID: 6a435eba7cb1
Revises: 8f9472f835f0
Create Date: 2024-08-23 10:43:19.202271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a435eba7cb1'
down_revision: Union[str, None] = '8f9472f835f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('admin_notify', mysql.TINYINT(), nullable=True, comment='1->Notify,2->Read'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_history', 'admin_notify')
    # ### end Alembic commands ###
