"""add ad table

Revision ID: 6c7b59266728
Revises: 4c2dc8997dc8
Create Date: 2024-07-16 17:39:57.326883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c7b59266728'
down_revision: Union[str, None] = '4c2dc8997dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journalfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True, comment='journal tab id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journalfiles')
    # ### end Alembic commands ###
