"""Update article table schema

Revision ID: 6cf745cee47a
Revises: 197aa35e085d
Create Date: 2024-07-17 12:10:33.140382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cf745cee47a'
down_revision: Union[str, None] = '197aa35e085d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('article', 'media_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('media_path', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('article', 'description')
    # ### end Alembic commands ###
