"""dfds

Revision ID: 6e8e5e0495f3
Revises: 5ddad25ce512
Create Date: 2024-07-22 15:29:43.238107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e8e5e0495f3'
down_revision: Union[str, None] = '5ddad25ce512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('img_path', sa.String(length=500), nullable=True))
    op.drop_column('media_files', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('file_path', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('media_files', 'img_path')
    # ### end Alembic commands ###
