"""add user details  column in user table

Revision ID: 6e9cb49ccc3a
Revises: 07a8edce6bdd
Create Date: 2024-07-26 10:01:41.373082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9cb49ccc3a'
down_revision: Union[str, None] = '07a8edce6bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
