"""add creatde by in OrderStatusHistory table

Revision ID: 7062ce7bb9d3
Revises: 223cf713af5c
Create Date: 2024-08-27 10:14:45.222912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7062ce7bb9d3'
down_revision: Union[str, None] = '223cf713af5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('header_image', sa.String(length=500), nullable=True))
    op.add_column('article', sa.Column('middle_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'middle_image')
    op.drop_column('article', 'header_image')
    # ### end Alembic commands ###
