"""add user details  column in user table

Revision ID: 70c249802f19
Revises: a96916e098ed
Create Date: 2024-07-26 14:37:42.869749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '70c249802f19'
down_revision: Union[str, None] = 'a96916e098ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_paid', mysql.TINYINT(), nullable=True, comment='1-pending,2-Paid'))
    op.drop_column('user', 'is_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_paid', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-pending,2-Paid'))
    op.drop_column('article', 'is_paid')
    # ### end Alembic commands ###
