"""add user details  column in user table

Revision ID: 71404d1b056f
Revises: 208c09b11f32
Create Date: 2024-07-26 15:03:58.734789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71404d1b056f'
down_revision: Union[str, None] = '208c09b11f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment',
               existing_nullable=True)
    # ### end Alembic commands ###
