"""add ad table

Revision ID: 725811f979a8
Revises: ff9144ce57f4
Create Date: 2024-07-16 16:03:24.525464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '725811f979a8'
down_revision: Union[str, None] = 'ff9144ce57f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=250), nullable=True),
    sa.Column('meta_keywords', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('media_path', sa.String(length=500), nullable=True),
    sa.Column('title_approved', mysql.TINYINT(), nullable=True, comment='0->waiting,1->SE approved,2-CE Approved'),
    sa.Column('content_approved', mysql.TINYINT(), nullable=True, comment='0->waiting,1->SE approved,2-CE Approved'),
    sa.Column('sub_editor_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('chief_editor_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['chief_editor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sub_editor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal')
    # ### end Alembic commands ###
