"""add is_active in category table

Revision ID: 7668194d8f00
Revises: 8e8f0a4c9efc
Create Date: 2024-07-31 10:11:13.618189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7668194d8f00'
down_revision: Union[str, None] = '8e8f0a4c9efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_settings', 'no_advertisement_available_image')
    op.alter_column('media_files', 'content_type',
               existing_type=mysql.TINYINT(),
               comment='1->Advertisement,2->Banners,3-youtupe',
               existing_comment='1->Advertisement,2->Banners',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_files', 'content_type',
               existing_type=mysql.TINYINT(),
               comment='1->Advertisement,2->Banners',
               existing_comment='1->Advertisement,2->Banners,3-youtupe',
               existing_nullable=True)
    op.add_column('cms_settings', sa.Column('no_advertisement_available_image', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
