"""add file type in article files

Revision ID: 76f1604405ac
Revises: 1c8630c2d8c2
Create Date: 2024-08-05 17:33:15.131158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '76f1604405ac'
down_revision: Union[str, None] = '1c8630c2d8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('img_type', mysql.TINYINT(), nullable=True, comment='1->png,0->jpg,3-jpeg'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'img_type')
    # ### end Alembic commands ###
