"""add file type in article files

Revision ID: 7ae4238fca06
Revises: 0a6590695ba4
Create Date: 2024-08-01 12:50:25.540408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ae4238fca06'
down_revision: Union[str, None] = '0a6590695ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('youtube_link', sa.String(length=500), nullable=True))
    op.drop_column('article', 'youtupe_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('youtupe_link', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('article', 'youtube_link')
    # ### end Alembic commands ###
