"""add creatde by in OrderStatusHistory table

Revision ID: 7b4bebc8a737
Revises: 97669d9b10c4
Create Date: 2024-08-27 16:03:57.814697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4bebc8a737'
down_revision: Union[str, None] = '97669d9b10c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('brand_name', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'brand_name')
    # ### end Alembic commands ###
