"""dfds

Revision ID: 845056b26359
Revises: 10ad4186d210
Create Date: 2024-07-19 14:54:35.595768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '845056b26359'
down_revision: Union[str, None] = '10ad4186d210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Resend Otp',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Resend Otp',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password',
               existing_nullable=True)
    # ### end Alembic commands ###
