"""add creatde by in OrderStatusHistory table

Revision ID: 847bf5ef8cec
Revises: 54d480da8f7f
Create Date: 2024-08-23 15:55:44.409937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '847bf5ef8cec'
down_revision: Union[str, None] = '54d480da8f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('request_user', mysql.TINYINT(), nullable=True, comment='1->Yes,2->No'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'request_user')
    # ### end Alembic commands ###
