"""add editor choice column in article table

Revision ID: 8625d6ba9ab9
Revises: e82e5d3116cd
Create Date: 2024-07-27 09:37:18.735787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8625d6ba9ab9'
down_revision: Union[str, None] = 'e82e5d3116cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('editors_choice', mysql.TINYINT(), nullable=True, comment='1->No,2->yes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'editors_choice')
    # ### end Alembic commands ###
