"""add creatde by in OrderStatusHistory table

Revision ID: 87ed6aabe6c9
Revises: f8a0899448c8
Create Date: 2024-08-28 10:08:44.198085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87ed6aabe6c9'
down_revision: Union[str, None] = 'f8a0899448c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_files', 'is_top_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_files', sa.Column('is_top_image', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->yes'))
    # ### end Alembic commands ###
