"""add creatde by in OrderStatusHistory table

Revision ID: 89d21ca45122
Revises: d85c04b1cf12
Create Date: 2024-08-28 09:49:00.225578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89d21ca45122'
down_revision: Union[str, None] = 'd85c04b1cf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_files', sa.Column('is_top_image', mysql.TINYINT(), nullable=True, comment='1->yes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_files', 'is_top_image')
    # ### end Alembic commands ###
