"""add ad table

Revision ID: 8a1683d996b6
Revises: d6a301c64647
Create Date: 2024-07-17 16:55:10.516821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a1683d996b6'
down_revision: Union[str, None] = 'd6a301c64647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='journal tab id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('articlefiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articlefiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img_path', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('img_alter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('article_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='journal tab id'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name='articlefiles_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='articlefiles_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('article_files')
    # ### end Alembic commands ###
