"""add ad table

Revision ID: 8c5030c120fb
Revises: 520a763e16b2
Create Date: 2024-07-16 16:29:51.074845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c5030c120fb'
down_revision: Union[str, None] = '520a763e16b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('topic', sa.String(length=250), nullable=True))
    op.add_column('journal', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('journal', sa.Column('topic_approved', mysql.TINYINT(), nullable=True, comment='0->waiting,1->SE approved,2-CE Approved'))
    op.drop_column('journal', 'title')
    op.drop_column('journal', 'title_approved')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('title_approved', mysql.TINYINT(), autoincrement=False, nullable=True, comment='0->waiting,1->SE approved,2-CE Approved'))
    op.add_column('journal', sa.Column('title', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('journal', 'topic_approved')
    op.drop_column('journal', 'comment')
    op.drop_column('journal', 'topic')
    # ### end Alembic commands ###
