"""Update article table schema

Revision ID: 8cb511435f9c
Revises: 52bbd4d5ada2
Create Date: 2024-07-17 11:35:13.323558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8cb511435f9c'
down_revision: Union[str, None] = '52bbd4d5ada2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=250), nullable=True),
    sa.Column('img_path', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='sub category order no'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='category tab id'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('subcategory')
    op.add_column('article', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'sub_category', ['sub_category_id'], ['id'])
    op.create_foreign_key(None, 'article', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'sub_category_id')
    op.drop_column('article', 'category_id')
    op.create_table('subcategory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('seo_url', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('img_alter', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('img_path', mysql.TEXT(), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='sub category order no'),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='category tab id'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='subcategory_ibfk_1'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='subcategory_ibfk_2'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='subcategory_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('sub_category')
    # ### end Alembic commands ###
