"""add ad table

Revision ID: 8d19ffef2cc4
Revises: 725811f979a8
Create Date: 2024-07-16 16:21:51.311129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d19ffef2cc4'
down_revision: Union[str, None] = '725811f979a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('is_journalist', mysql.TINYINT(), nullable=True, comment='1-yes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'is_journalist')
    # ### end Alembic commands ###
