"""add ad table

Revision ID: 8d80cc7bfd4c
Revises: fc8279284d2f
Create Date: 2024-07-16 15:39:22.450590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d80cc7bfd4c'
down_revision: Union[str, None] = 'fc8279284d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brandcampaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('media_path', sa.Text(), nullable=True),
    sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->image,2->Gif'),
    sa.Column('brand_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='brand campaigngs order no'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brandcampaigns')
    # ### end Alembic commands ###
