"""add is_active in category table

Revision ID: 8e8f0a4c9efc
Revises: 56268281acfb
Create Date: 2024-07-30 10:16:37.795195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e8f0a4c9efc'
down_revision: Union[str, None] = '56268281acfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_category', sa.Column('is_active', mysql.TINYINT(), nullable=True, comment='1->active,0->inactive'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_category', 'is_active')
    # ### end Alembic commands ###
