"""add creatde by in OrderStatusHistory table

Revision ID: 961f8f66eb1e
Revises: 1941e6482dba
Create Date: 2024-08-24 11:54:10.585912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '961f8f66eb1e'
down_revision: Union[str, None] = '1941e6482dba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'save_for_later')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('save_for_later', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->yes'))
    # ### end Alembic commands ###
