"""add creatde by in OrderStatusHistory table

Revision ID: 9621b915bd99
Revises: aec7f007d9b0
Create Date: 2024-08-23 12:08:11.142672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9621b915bd99'
down_revision: Union[str, None] = 'aec7f007d9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_topic', sa.Column('is_approved', mysql.TINYINT(), nullable=True, comment='1->no,2-yes'))
    op.add_column('article_topic', sa.Column('approved_by', sa.Integer(), nullable=True, comment='user id'))
    op.create_foreign_key(None, 'article_topic', 'user', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_topic', type_='foreignkey')
    op.drop_column('article_topic', 'approved_by')
    op.drop_column('article_topic', 'is_approved')
    # ### end Alembic commands ###
