"""add creatde by in OrderStatusHistory table

Revision ID: 96929ce4768d
Revises: 961f8f66eb1e
Create Date: 2024-08-24 11:54:29.262470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96929ce4768d'
down_revision: Union[str, None] = '961f8f66eb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('save_for_later', mysql.TINYINT(display_width=0), nullable=True, comment='1->yes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'save_for_later')
    # ### end Alembic commands ###
