"""add creatde by in OrderStatusHistory table

Revision ID: 97669d9b10c4
Revises: 00befab20251
Create Date: 2024-08-27 16:03:37.365288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97669d9b10c4'
down_revision: Union[str, None] = '00befab20251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
