"""add creatde by in OrderStatusHistory table

Revision ID: 986c601190f7
Revises: ad87207d2ffa
Create Date: 2024-08-27 15:07:13.398130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '986c601190f7'
down_revision: Union[str, None] = 'ad87207d2ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('se_header_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('se_middle_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('se_footer_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('ce_header_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('ce_middle_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('ce_footer_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'ce_footer_checkbox')
    op.drop_column('article', 'ce_middle_checkbox')
    op.drop_column('article', 'ce_header_checkbox')
    op.drop_column('article', 'se_footer_checkbox')
    op.drop_column('article', 'se_middle_checkbox')
    op.drop_column('article', 'se_header_checkbox')
    # ### end Alembic commands ###
