"""add creatde by in OrderStatusHistory table

Revision ID: 997660209628
Revises: 1a77b5500279
Create Date: 2024-08-28 18:19:55.083048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997660209628'
down_revision: Union[str, None] = '1a77b5500279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'media_top_images', 'media_files', ['media_files_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_top_images', type_='foreignkey')
    # ### end Alembic commands ###
