"""dffds

Revision ID: 99efd316831e
Revises: b24ff8d92892
Create Date: 2024-08-10 17:47:23.625125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99efd316831e'
down_revision: Union[str, None] = 'b24ff8d92892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_topic', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article_topic', 'sub_category', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_topic', type_='foreignkey')
    op.drop_column('article_topic', 'sub_category_id')
    # ### end Alembic commands ###
