"""add creatde by in OrderStatusHistory table

Revision ID: 9a209ca5ea40
Revises: 6957cda7828c
Create Date: 2024-08-23 12:40:23.730591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a209ca5ea40'
down_revision: Union[str, None] = '6957cda7828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('media_position', mysql.TINYINT(), nullable=True, comment='1->Top,2-Bottom,3-right,4-Left'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'media_position')
    # ### end Alembic commands ###
