"""add creatde by in OrderStatusHistory table

Revision ID: 9bb195f54e6b
Revises: 7808bf0155ed
Create Date: 2024-08-28 18:07:19.141278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9bb195f54e6b'
down_revision: Union[str, None] = '7808bf0155ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='article tab id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='user tab id'),
    sa.Column('email_type', mysql.TINYINT(), nullable=True, comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_history')
    # ### end Alembic commands ###
