"""add user details  column in user table

Revision ID: 9c31b32dfa35
Revises: 39ba1a8d5b0d
Create Date: 2024-07-26 11:40:54.729108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c31b32dfa35'
down_revision: Union[str, None] = '39ba1a8d5b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joining_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'joining_date')
    # ### end Alembic commands ###
