"""add group and designation

Revision ID: 9c466aaf4822
Revises: c528a0f82bf6
Create Date: 2024-09-04 10:15:57.519117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c466aaf4822'
down_revision: Union[str, None] = 'c528a0f82bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_files', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_files', 'description')
    # ### end Alembic commands ###
