"""Update article table schema

Revision ID: 9cf015f6ddc2
Revises: 6cf745cee47a
Create Date: 2024-07-17 14:04:30.558470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9cf015f6ddc2'
down_revision: Union[str, None] = '6cf745cee47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=250), nullable=True),
    sa.Column('img_path', sa.Text(), nullable=True),
    sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->image,2->Gif'),
    sa.Column('brand_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='brand campaigngs order no'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('meta_title', sa.String(length=250), nullable=True),
    sa.Column('meta_description', sa.String(length=250), nullable=True),
    sa.Column('meta_keywords', sa.String(length=250), nullable=True),
    sa.Column('seo_url', sa.String(length=250), nullable=True),
    sa.Column('img_alter', sa.String(length=255), nullable=True),
    sa.Column('content_type', mysql.TINYINT(), nullable=True, comment='1->Advertisement,2->others'),
    sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->shorts,2->Video'),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('brandcampaigns')
    op.drop_table('mediafiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediafiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('meta_title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('meta_description', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('meta_keywords', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('seo_url', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('img_alter', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->Advertisement,2->others'),
    sa.Column('media_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->shorts,2->Video'),
    sa.Column('media_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='mediafiles_ibfk_1'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='mediafiles_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('brandcampaigns',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('img_alter', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('img_path', mysql.TEXT(), nullable=True),
    sa.Column('media_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->image,2->Gif'),
    sa.Column('brand_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='brand campaigngs order no'),
    sa.Column('status', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at.strftime("%Y-%m-%d %H:%M:%S")', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='brandcampaigns_ibfk_1'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='brandcampaigns_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('media_files')
    op.drop_table('brand_campaigns')
    # ### end Alembic commands ###
