"""Initial migration

Revision ID: 9def590ef5cc
Revises: 65ac1a6cb216
Create Date: 2024-09-18 10:52:24.641842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9def590ef5cc'
down_revision: Union[str, None] = '65ac1a6cb216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('img_path', sa.String(length=2000), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('series_type', mysql.TINYINT(), nullable=True, comment='1-Parent, 2-child'),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='pro_stories id'),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pro_stories.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pro_series')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_series',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('img_path', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='pro_series id'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'),
    sa.Column('series_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1-Parent, 2-child'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='pro_series_ibfk_1'),
    sa.ForeignKeyConstraint(['parent_id'], ['pro_series.id'], name='pro_series_ibfk_2'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], name='pro_series_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pro_stories')
    # ### end Alembic commands ###
