"""Initial migration

Revision ID: a2fc87ae1c03
Revises: 5363c71c2070
Create Date: 2024-09-28 15:18:56.742635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2fc87ae1c03'
down_revision: Union[str, None] = '5363c71c2070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'))
    op.create_foreign_key(None, 'ratings', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'updated_by')
    # ### end Alembic commands ###
