"""add user details  column in user table

Revision ID: a96916e098ed
Revises: f4dc6ee1e393
Create Date: 2024-07-26 14:24:06.734733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a96916e098ed'
down_revision: Union[str, None] = 'f4dc6ee1e393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('employement_type', mysql.TINYINT(), nullable=True, comment='1-full-time, 2-part-time, 3-contract, 4-internship, 5-temporary'),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('requirements', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('careers')
    # ### end Alembic commands ###
