"""add ad table

Revision ID: ac3b61f91116
Revises: 5afa5eb3b4d4
Create Date: 2024-07-16 14:53:27.435613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac3b61f91116'
down_revision: Union[str, None] = '5afa5eb3b4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('media_type', mysql.TINYINT(), nullable=True, comment='1->shorts,-1->Video'))
    op.drop_column('advertisement', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('file_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->shorts,-1->Video'))
    op.drop_column('advertisement', 'media_type')
    # ### end Alembic commands ###
