"""add file type in article files

Revision ID: ac45c587ee4d
Revises: 47c49fd8430c
Create Date: 2024-08-05 10:10:17.799321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac45c587ee4d'
down_revision: Union[str, None] = '47c49fd8430c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('topic_approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'topic_approved_at')
    # ### end Alembic commands ###
