"""dffds

Revision ID: ac857409ba66
Revises: 39192077214d
Create Date: 2024-08-09 17:07:01.373674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac857409ba66'
down_revision: Union[str, None] = '39192077214d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('designation_type', mysql.TINYINT(), nullable=True, comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6-Technical Lead,7->Digital Marketing strategist,8-journalist,,9-SEO-Google Strategist,10-Marketing,11-Web designer,12-Graphic Designer'))
    op.drop_column('careers', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('job_type', mysql.TINYINT(), autoincrement=False, nullable=True, comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6-Technical Lead,7->Digital Marketing strategist,8-journalist,,9-SEO-Google Strategist,10-Marketing,11-Web designer,12-Graphic Designer'))
    op.drop_column('careers', 'designation_type')
    # ### end Alembic commands ###
