"""add creatde by in OrderStatusHistory table

Revision ID: ad87207d2ffa
Revises: 7062ce7bb9d3
Create Date: 2024-08-27 10:30:24.077288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad87207d2ffa'
down_revision: Union[str, None] = '7062ce7bb9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('media_page', mysql.TINYINT(), nullable=True, comment='1->Home,2-Category'))
    op.add_column('media_files', sa.Column('is_google_ad', mysql.TINYINT(), nullable=True, comment='1->yes,0-No'))
    op.add_column('media_files', sa.Column('top_image', sa.String(length=500), nullable=True))
    op.add_column('media_files', sa.Column('left_image', sa.String(length=500), nullable=True))
    op.add_column('media_files', sa.Column('right_image', sa.String(length=500), nullable=True))
    op.add_column('media_files', sa.Column('bottom_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_files', 'bottom_image')
    op.drop_column('media_files', 'right_image')
    op.drop_column('media_files', 'left_image')
    op.drop_column('media_files', 'top_image')
    op.drop_column('media_files', 'is_google_ad')
    op.drop_column('media_files', 'media_page')
    # ### end Alembic commands ###
