"""add article title in article

Revision ID: ae17c105253b
Revises: 99f64a8b3e9e
Create Date: 2024-07-29 17:41:30.256561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae17c105253b'
down_revision: Union[str, None] = '99f64a8b3e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'published_at')
    # ### end Alembic commands ###
