"""add creatde by in OrderStatusHistory table

Revision ID: aec7f007d9b0
Revises: 6a435eba7cb1
Create Date: 2024-08-23 11:00:23.169030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aec7f007d9b0'
down_revision: Union[str, None] = '6a435eba7cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='article tab id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('admin_id', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('admin_notify', mysql.TINYINT(), nullable=True, comment='1->Notify,2->Read'),
    sa.Column('journalist_notify', mysql.TINYINT(), nullable=True, comment='1->Notify,2->Read'),
    sa.Column('topic_status', mysql.TINYINT(), nullable=True, comment='1->new,2-review,3-comment,4->approved'),
    sa.Column('content_status', mysql.TINYINT(), nullable=True, comment='1->new,2-review,3-comment,4->approved'),
    sa.Column('notification_type', mysql.TINYINT(), nullable=True, comment='1->topic,2-content,3-Requested Account'),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
