"""dfds

Revision ID: b0a88e730c7c
Revises: ebbe681f15c3
Create Date: 2024-07-19 14:44:28.045487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0a88e730c7c'
down_revision: Union[str, None] = 'ebbe681f15c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Otp,4->Reset Password',
               existing_comment='1->Journalist acc,2->Article,0->inactive',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist acc,2->Article,0->inactive',
               existing_comment='1->Journalist Account,2->Article,3->Otp,4->Reset Password',
               existing_nullable=True)
    # ### end Alembic commands ###
