"""add user and apitoken table

Revision ID: b173c5bdcf91
Revises: f97843ca9bee
Create Date: 2024-07-16 12:30:55.624267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b173c5bdcf91'
down_revision: Union[str, None] = 'f97843ca9bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alternative_no', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('approval_status', mysql.TINYINT(), nullable=True, comment='1->Accepted,0->Request,-1 ->rejected'))
    op.add_column('user', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'user', 'states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    op.drop_column('user', 'state_id')
    op.drop_column('user', 'approval_status')
    op.drop_column('user', 'alternative_no')
    # ### end Alembic commands ###
