"""dffds

Revision ID: b24ff8d92892
Revises: ac857409ba66
Create Date: 2024-08-10 15:55:47.014785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b24ff8d92892'
down_revision: Union[str, None] = 'ac857409ba66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('careers', 'salary',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('careers', 'salary',
               existing_type=sa.DECIMAL(precision=12, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
