"""add user details  column in user table

Revision ID: b4422308ec6c
Revises: b4ffec1f8b06
Create Date: 2024-07-26 12:49:14.804905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4422308ec6c'
down_revision: Union[str, None] = 'b4ffec1f8b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_paid', mysql.TINYINT(), nullable=True, comment='1-pending,2-Paid'))
    op.alter_column('user', 'is_request',
               existing_type=mysql.TINYINT(),
               comment='1->Request,2-Accpted,3-Interview Process,-1 ->rejected',
               existing_comment='1->Interview Process,2->Accepted,0->Request,-1 ->rejected',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_request',
               existing_type=mysql.TINYINT(),
               comment='1->Interview Process,2->Accepted,0->Request,-1 ->rejected',
               existing_comment='1->Request,2-Accpted,3-Interview Process,-1 ->rejected',
               existing_nullable=True)
    op.drop_column('user', 'is_paid')
    # ### end Alembic commands ###
