"""add user details  column in user table

Revision ID: b4ffec1f8b06
Revises: ea570be4e187
Create Date: 2024-07-26 12:32:19.068135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4ffec1f8b06'
down_revision: Union[str, None] = 'ea570be4e187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->SE approved,5-CE Approved',
               existing_comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_nullable=True)
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved)',
               existing_comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved)',
               existing_nullable=True)
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='0-not submitted,1->new,2->SE approved,3-CE Approved,4-On Hold',
               existing_comment='1->new,2-review,3-comment,4->SE approved,5-CE Approved',
               existing_nullable=True)
    # ### end Alembic commands ###
