"""add ad table

Revision ID: b7f5b40d3d72
Revises: fcb54d940d12
Create Date: 2024-07-17 16:49:47.236423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7f5b40d3d72'
down_revision: Union[str, None] = 'fcb54d940d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'states', ['state_id'], ['id'])
    op.create_foreign_key(None, 'article', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'cities', 'states', ['state_id'], ['id'])
    op.drop_column('cities', 'district_id')
    op.add_column('user', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'states', ['state_id'], ['id'])
    op.create_foreign_key(None, 'user', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    op.drop_column('user', 'state_id')
    op.add_column('cities', sa.Column('district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'city_id')
    op.drop_column('article', 'state_id')
    # ### end Alembic commands ###
