"""add reward point

Revision ID: bb82534d2fcc
Revises: a2fc87ae1c03
Create Date: 2024-10-09 16:54:22.605717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb82534d2fcc'
down_revision: Union[str, None] = 'a2fc87ae1c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('careers', 'salary',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment,7-newsletter',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment',
               existing_nullable=True)
    op.alter_column('website_forms', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('website_forms', 'service_type',
               existing_type=mysql.TINYINT(),
               comment='6-Payment',
               existing_comment='1 -> Advertisement,\\r\\n2 -> Brand Campaign',
               existing_nullable=True)
    op.alter_column('website_forms', 'form_type',
               existing_type=mysql.TINYINT(),
               comment=' \t1 -> AD/Brand form, 2 -> contact form 3 -> newsletter \t',
               existing_comment='1 -> AD/Brand form,\\r\\n2 -> contact form\\r\\n3 -> newsletter',
               existing_nullable=True)
    op.alter_column('website_forms', 'status',
               existing_type=mysql.TINYINT(),
               nullable=True,
               comment='1-active',
               existing_comment='1 -> Active,\\r\\n0 -> Inactive\\r\\n-1 -> Deleted',
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_forms', 'status',
               existing_type=mysql.TINYINT(),
               nullable=False,
               comment='1 -> Active,\\r\\n0 -> Inactive\\r\\n-1 -> Deleted',
               existing_comment='1-active',
               existing_server_default=sa.text("'1'"))
    op.alter_column('website_forms', 'form_type',
               existing_type=mysql.TINYINT(),
               comment='1 -> AD/Brand form,\\r\\n2 -> contact form\\r\\n3 -> newsletter',
               existing_comment=' \t1 -> AD/Brand form, 2 -> contact form 3 -> newsletter \t',
               existing_nullable=True)
    op.alter_column('website_forms', 'service_type',
               existing_type=mysql.TINYINT(),
               comment='1 -> Advertisement,\\r\\n2 -> Brand Campaign',
               existing_comment='6-Payment',
               existing_nullable=True)
    op.alter_column('website_forms', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('email_history', 'email_type',
               existing_type=mysql.TINYINT(),
               comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment',
               existing_comment='1->Journalist Account,2->Article,3->Forget Password,4->Reset Password,5-signup,6-Payment,7-newsletter',
               existing_nullable=True)
    op.alter_column('careers', 'salary',
               existing_type=sa.String(length=500),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
