"""add article title in article

Revision ID: c20ddec7c851
Revises: 8625d6ba9ab9
Create Date: 2024-07-29 09:20:00.082058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20ddec7c851'
down_revision: Union[str, None] = '8625d6ba9ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_title', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_title')
    # ### end Alembic commands ###
