"""add is_active in category table

Revision ID: c4375c959677
Revises: 0ac3e03a2911
Create Date: 2024-07-31 17:32:18.417446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4375c959677'
down_revision: Union[str, None] = '0ac3e03a2911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('article', sa.Column('footer_content', sa.String(length=<class 'sqlalchemy.sql.sqltypes.Text'>), nullable=True))
    # op.add_column('article', sa.Column('header_content', sa.String(length=<class 'sqlalchemy.sql.sqltypes.Text'>), nullable=True))
    # op.add_column('article', sa.Column('middle_content', sa.String(length=<class 'sqlalchemy.sql.sqltypes.Text'>), nullable=True))
    # op.alter_column('article', 'content',
    #            existing_type=mysql.VARCHAR(length=2500),
    #            type_=sa.String(length=250),
    #            existing_nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('article', 'content',
    #            existing_type=sa.String(length=250),
    #            type_=mysql.VARCHAR(length=2500),
    #            existing_nullable=True)
    # op.drop_column('article', 'middle_content')
    # op.drop_column('article', 'header_content')
    # op.drop_column('article', 'footer_content')
    # ### end Alembic commands ###
    pass