"""add creatde by in OrderStatusHistory table

Revision ID: c4c02040bf67
Revises: 515c8348d2ec
Create Date: 2024-08-22 13:49:40.053733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4c02040bf67'
down_revision: Union[str, None] = '515c8348d2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('topic_se_approved', mysql.TINYINT(), nullable=True, comment='1->new,2-review,3-comment,4->SE approved'))
    op.add_column('article', sa.Column('content_se_approved', mysql.TINYINT(), nullable=True, comment='1->new,2-review,3-comment,4->SE approved'))
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->CE Approved',
               existing_comment='1->new,2-review,3-comment,4->SE approved,5-CE Approved',
               existing_nullable=True)
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->-Published(CE Approved)',
               existing_comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->SE approved,5-Published(CE Approved)',
               existing_comment='1->new,2-review,3-comment,4->-Published(CE Approved)',
               existing_nullable=True)
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='1->new,2-review,3-comment,4->SE approved,5-CE Approved',
               existing_comment='1->new,2-review,3-comment,4->CE Approved',
               existing_nullable=True)
    op.drop_column('article', 'content_se_approved')
    op.drop_column('article', 'topic_se_approved')
    # ### end Alembic commands ###
