"""initial commit

Revision ID: c528a0f82bf6
Revises: c2c2d634a981
Create Date: 2024-09-02 12:51:20.831733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c528a0f82bf6'
down_revision: Union[str, None] = 'c2c2d634a981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('header_image_description', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('middle_image_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'middle_image_description')
    op.drop_column('article', 'header_image_description')
    # ### end Alembic commands ###
