"""add user and apitoken table

Revision ID: cb5ffeb72d10
Revises: 603372772341
Create Date: 2024-07-16 12:56:12.866535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5ffeb72d10'
down_revision: Union[str, None] = '603372772341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'updated_by')
    # ### end Alembic commands ###
