"""Update article table schema

Revision ID: cce567dd9b8e
Revises: d6aa0a81d40e
Create Date: 2024-07-17 15:18:05.397218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cce567dd9b8e'
down_revision: Union[str, None] = 'd6aa0a81d40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articlehistory', sa.Column('journalist_id', sa.Integer(), nullable=True, comment='user id'))
    op.drop_constraint('articlehistory_ibfk_4', 'articlehistory', type_='foreignkey')
    op.create_foreign_key(None, 'articlehistory', 'user', ['journalist_id'], ['id'])
    op.drop_column('articlehistory', 'jouranlist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articlehistory', sa.Column('jouranlist_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='user id'))
    op.drop_constraint(None, 'articlehistory', type_='foreignkey')
    op.create_foreign_key('articlehistory_ibfk_4', 'articlehistory', 'user', ['jouranlist_id'], ['id'])
    op.drop_column('articlehistory', 'journalist_id')
    # ### end Alembic commands ###
