"""add user details  column in user table

Revision ID: ce2df79e776b
Revises: 6e9cb49ccc3a
Create Date: 2024-07-26 10:01:55.892912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2df79e776b'
down_revision: Union[str, None] = '6e9cb49ccc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('aadhaar_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'aadhaar_number')
    # ### end Alembic commands ###
