"""Initial migration

Revision ID: ce7fe23c6dd0
Revises: 348ef923d556
Create Date: 2024-09-24 14:19:28.059181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce7fe23c6dd0'
down_revision: Union[str, None] = '348ef923d556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_files', 'raw_file',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_files', 'raw_file',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
