"""add ad table

Revision ID: d04be0db6384
Revises: 8a1683d996b6
Create Date: 2024-07-17 17:44:15.787565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd04be0db6384'
down_revision: Union[str, None] = '8a1683d996b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('status', mysql.TINYINT(), nullable=True, comment='1->active,-1->deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'status')
    # ### end Alembic commands ###
