"""Initial migration

Revision ID: d069d952330a
Revises: 9c466aaf4822
Create Date: 2024-09-18 09:14:36.001992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd069d952330a'
down_revision: Union[str, None] = '9c466aaf4822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pro_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('img_path', sa.String(length=2000), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('seies_type', mysql.TINYINT(), nullable=True, comment='1-Parent, 2-child'),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='pro_series id'),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True, comment='1-active, -1 inactive, 0- deleted'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='user id'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='user id'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pro_series.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('article_history', 'history_type',
               existing_type=mysql.TINYINT(),
               comment='1->topic,2-content,3-editors_topic,4-Overdue',
               existing_comment='1->topic,2-content,3-editors_topic',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_history', 'history_type',
               existing_type=mysql.TINYINT(),
               comment='1->topic,2-content,3-editors_topic',
               existing_comment='1->topic,2-content,3-editors_topic,4-Overdue',
               existing_nullable=True)
    op.drop_table('pro_series')
    # ### end Alembic commands ###
