"""Update article table schema

Revision ID: d6aa0a81d40e
Revises: 9cf015f6ddc2
Create Date: 2024-07-17 15:01:28.726908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6aa0a81d40e'
down_revision: Union[str, None] = '9cf015f6ddc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='0->new,1->SE approved,2-CE Approved,3-On Hold',
               existing_comment='0->waiting,1->SE approved,2-CE Approved,3-Published,4-holding',
               existing_nullable=True)
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='0->new,1->SE approved,2-CE Approved,3-On Hold',
               existing_comment='0->waiting,1->SE approved,2-CE Approved,3-published,4-holding',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content_approved',
               existing_type=mysql.TINYINT(),
               comment='0->waiting,1->SE approved,2-CE Approved,3-published,4-holding',
               existing_comment='0->new,1->SE approved,2-CE Approved,3-On Hold',
               existing_nullable=True)
    op.alter_column('article', 'topic_approved',
               existing_type=mysql.TINYINT(),
               comment='0->waiting,1->SE approved,2-CE Approved,3-Published,4-holding',
               existing_comment='0->new,1->SE approved,2-CE Approved,3-On Hold',
               existing_nullable=True)
    # ### end Alembic commands ###
