"""add creatde by in OrderStatusHistory table

Revision ID: e04a9bb3a034
Revises: 08ace977cb29
Create Date: 2024-08-23 16:51:19.695089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e04a9bb3a034'
down_revision: Union[str, None] = '08ace977cb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('title', sa.String(length=500), nullable=True))
    op.drop_column('article_history', 'article_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_history', sa.Column('article_state', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('article_history', 'title')
    # ### end Alembic commands ###
