"""add creatde by in OrderStatusHistory table

Revision ID: e569599a52dd
Revises: 14eb52bd30e0
Create Date: 2024-08-28 18:04:46.257417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e569599a52dd'
down_revision: Union[str, None] = '14eb52bd30e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
