"""add creatde by in OrderStatusHistory table

Revision ID: e9dfedf67d96
Revises: e4d63fcf7639
Create Date: 2024-08-29 15:50:19.918114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9dfedf67d96'
down_revision: Union[str, None] = 'e4d63fcf7639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('se_header_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('se_middle_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('se_footer_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('ce_header_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('ce_middle_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    op.add_column('article', sa.Column('ce_footer_checkbox', mysql.TINYINT(), nullable=True, comment='1-checked'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'ce_footer_checkbox')
    op.drop_column('article', 'ce_middle_checkbox')
    op.drop_column('article', 'ce_header_checkbox')
    op.drop_column('article', 'se_footer_checkbox')
    op.drop_column('article', 'se_middle_checkbox')
    op.drop_column('article', 'se_header_checkbox')
    # ### end Alembic commands ###
