"""dfds

Revision ID: e9f67a840be0
Revises: 845056b26359
Create Date: 2024-07-22 15:06:35.661187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f67a840be0'
down_revision: Union[str, None] = '845056b26359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img_alter', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'img_alter')
    # ### end Alembic commands ###
