"""add user details  column in user table

Revision ID: ea570be4e187
Revises: 456c67ede120
Create Date: 2024-07-26 12:10:25.063712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea570be4e187'
down_revision: Union[str, None] = '456c67ede120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'content',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=2500),
               existing_nullable=True)
    op.drop_column('article', 'article_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_content', mysql.VARCHAR(length=2500), nullable=True))
    op.alter_column('article', 'content',
               existing_type=sa.String(length=2500),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###
