"""dfds

Revision ID: ebbe681f15c3
Revises: 3cf7c8c2cedb
Create Date: 2024-07-19 14:14:21.413572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebbe681f15c3'
down_revision: Union[str, None] = '3cf7c8c2cedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_history', sa.Column('email_type', mysql.TINYINT(), nullable=True, comment='1->Journalist acc,2->Article,0->inactive'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_history', 'email_type')
    # ### end Alembic commands ###
