"""add user details  column in user table

Revision ID: efd67a3931b4
Revises: 6f5a03c8d1ed
Create Date: 2024-07-26 12:06:36.672689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd67a3931b4'
down_revision: Union[str, None] = '6f5a03c8d1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'article_topic', ['article_topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'article_topic_id')
    # ### end Alembic commands ###
