"""add new usertype

Revision ID: f19e90e9c9a0
Revises: 29c499b21eb9
Create Date: 2024-07-26 09:46:00.967039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f19e90e9c9a0'
down_revision: Union[str, None] = '29c499b21eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6-Technical Lead,7->Digital Marketing strategist,8-journalist,9-Member,10-SEO-Google Strategist,11-Marketing,12-Web designer,13-Graphic Designer',
               existing_comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6-Technical Lead,7->Digital Marketing strategist,8-journalist,9-Member',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_type',
               existing_type=mysql.TINYINT(),
               comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6-Technical Lead,7->Digital Marketing strategist,8-journalist,9-Member',
               existing_comment='1->SuperAdmin,2->Admin,3->Hr,4->Chief Editor,5->Sub Editor,6-Technical Lead,7->Digital Marketing strategist,8-journalist,9-Member,10-SEO-Google Strategist,11-Marketing,12-Web designer,13-Graphic Designer',
               existing_nullable=True)
    # ### end Alembic commands ###
