"""add creatde by in OrderStatusHistory table

Revision ID: f703c928cabf
Revises: 0034169f9c7a
Create Date: 2024-08-23 14:06:31.947092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f703c928cabf'
down_revision: Union[str, None] = '0034169f9c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'paid_amount')
    # ### end Alembic commands ###
