"""add user and apitoken table

Revision ID: f97843ca9bee
Revises: b0bbd24f697a
Create Date: 2024-07-16 12:24:20.367487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f97843ca9bee'
down_revision: Union[str, None] = 'b0bbd24f697a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cities', 'states', ['state_id'], ['id'])
    op.drop_column('cities', 'district_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('district_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cities', type_='foreignkey')
    # ### end Alembic commands ###
