"""add ad table

Revision ID: fc8279284d2f
Revises: 47f4720a4a08
Create Date: 2024-07-16 15:16:52.313750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc8279284d2f'
down_revision: Union[str, None] = '47f4720a4a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisement', 'file_path')
    op.drop_column('advertisement', 'default_img_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('default_img_path', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('advertisement', sa.Column('file_path', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
